// Next writes these same references into `next-env.d.ts`, which is generated by
// `next build` / `next dev` and is gitignored. Without a committed copy,
// `tsc --noEmit` on a clean checkout cannot resolve static image imports such as
// `@/assets/images/naan-tandoor.jpg` — so `npm run verify`, which typechecks
// before it builds, fails on a fresh clone and in CI.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
